### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by hugoeustaquio** [nvim-treesitter/nvim-treesitter-refactor#16]
I wold like to choose the background color of hightlighted lines. My current init.vim is like:

```
require'nvim-treesitter.configs'.setup {
  refactor = {
    highlight_current_scope = {
      enable = true
    },
  },
}
```
My suggestion is to have a property named "color", as following:
```
require'nvim-treesitter.configs'.setup {
  refactor = {
    highlight_current_scope = {
      enable = true,
      color = gray
    },
  },
}
```

Thanks for the good work, I hope you guys like this feature request.

**Comment by gegoune** [comment]
I think `TSCurrentScope` is being used to highlight current scope. You can change/define that highlight group to your liking.

**Comment by hugoeustaquio** [comment]
That's right! I achieved what I wanted with 'hi! TSCurrentScope guibg=#022631'. Thanks!
