### ISSUE TITLE
Feature Request - goto definition for YAML alias/anchors

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter-refactor#18]
**Is your feature request related to a problem? Please describe.**
Working with large YAML files (e.g. some continuous integration configurations), anchors are a typical feature. It is a typical scenario that you are at an alias that merges an anchor and you want to now how the content looks the anchor refers to. As anchors are usually references multiple times in the same document, it is annoying to use tools like `*` or similar.

**Describe the solution you'd like**
I would be cool if you could use `goto_definition` on an alias to jump to the related anchor.

**Describe alternatives you've considered**
Using `*` many times (also causes trouble for anchors names that are not a single word like `my-anchor`)
Using include search like `[ <CTR-I` (also suffers from word boundaries and must not be accurate/correct)
The YAML language server apparently does not support such "definition" jumps as well.

**Comment by stsewd** [comment]
This needs to be changed in locals.scm (https://github.com/nvim-treesitter/nvim-treesitter/pull/1172) and in the parser itself (parse the name of the anchor/alias and the `*` `&` symbols by separate https://github.com/ikatyang/tree-sitter-yaml/issues/23) in order for go to definition to work

**Comment by weilbith** [comment]
Cool. Thanks for your work!
But just to be sure: this is not yet working, but got just kinda prepared. Right?

**Comment by stsewd** [comment]
> Cool. Thanks for your work!
> But just to be sure: this is not yet working, but got just kinda prepared. Right?

Isn't  fully working yet, yeah. https://github.com/ikatyang/tree-sitter-yaml/issues/23 needs to be addressed.

**Comment by weilbith** [comment]
Do I need to do something to make it work? Except of updating all treesitter plugins?

**Comment by stsewd** [comment]
> Do I need to do something to make it work? Except of updating all treesitter plugins?

You need to update the plugins and the parser `:TSUpdate`. You can also change the default mapping of goto_definition https://github.com/nvim-treesitter/nvim-treesitter-refactor#navigation

**Comment by gegoune** [comment]
I have everything most up to date, and with this configuration:

```lua
navigation = {
  enable = true,
  keymaps = {
    goto_definition_lsp_fallback = "<C-]>"
  }
}
```
and 
```lua
vim.api.nvim_buf_set_keymap(0, "n", "<C-]>", "<cmd>lua vim.lsp.buf.definition()<CR>", {noremap = true, silent = true})
```

pressing `C-]` one yaml's anchor does not move the cursor at all.

**Comment by stsewd** [comment]
Hi, this is my config

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all",
  refactor = {
    navigation = {
      enable = true,
      keymaps = {
        goto_definition = "gd",
      },
    },
  },
}
```

Make sure you have the latest version of the yaml parser installed `:TSInstall yaml`

This is the file I'm testing with


```yaml
Defaults: &defaults
  Company: foo
  Item: 123

Computer:
  <<: *defaults
  <<: *defaults
  Price: 3000
```

Setting the cursor under `*defaults` and pressing `gd` moves the cursor to `&defaults`.

I can see this doesn't work with `goto_definition_lsp_fallback`, but that looks like a bug in another part of the code, I don't use neovim's lsp, so I can be helpful with that option.

**Comment by stsewd** [comment]
@cloggier this should fix the lsp fallback https://github.com/nvim-treesitter/nvim-treesitter-refactor/pull/19
