### ISSUE TITLE
keeps usages highlight un-cleared, when cursor moves among sibiling usage node

### ISSUE THREAD

**Issue by haolian9** [nvim-treesitter/nvim-treesitter-refactor#21]
as now, every time CursorMoved, refactor.highlight_usages will clear_usage_highlights();
this behavior is fine, except when the cursor moves among same `usage node` (i dont known the exact name to describe it), let's consider the following type flow:
* stay in a keyword in &updattime, so we have a set of usage highlight
* `refactor.navigation.goto_next_usage` or goto_previous_usage or just `hl` in the keyword
* highlight cleared, after waiting &updatetime, hightlighted again

it is very inefficient, and highlight blinks (unless set &updatetime a small value) leads a bad experience.

can we keep the highlight highlighting when the usage node has not changed after cursor moved.

**Comment by stsewd** [comment]
Hi, I have implemented something like what you described in https://github.com/nvim-treesitter/nvim-treesitter-refactor/pull/22.

**Comment by haolian9** [comment]
I have tested it, really nice, highlight works more fluent now. :thumbsup:

**Comment by haolian9** [comment]
I left some comments on that pr without permission, sorry for my rude. @stsewd

**Comment by haolian9** [comment]
after all those days use, i found i did not need a smart or automatic definition highlighter, so I added some options to nvim-treesitter-refactor.highlight_definitions
* auto_highlight = false
* keymap = { highlight_usages = false, clear_usage_highlights = false }

i made a commit to [implement it](https://github.com/haolian9/nvim-treesitter-refactor/commit/f2db484f20c8285462974ac20010efc1f49a745c) in my fork.
