### ISSUE TITLE
keymap can be optional?

### ISSUE THREAD

**Issue by haolian9** [nvim-treesitter/nvim-treesitter-refactor#23]
both `refactor.{smart_rename, navigation}` have default keymap table, user can only choose what key to use for a function, but can not choose whether to use that function.

some functions I really not need, such as `navigation.list_definitions`, but I still have to allocate a keymap to it, and the keymap is `{noremap=true}`

So is it possible to make a keymap optional? like:

```
{
    refactor = {
        navigation = {
            keymaps = {
                list_definitions = false,
            }
        }
    }
}
```

**Comment by steelsojka** [comment]
The noop key map should work here `<nop>`

**Comment by weilbith** [comment]
This does not work for me when I set multiple mappings to this.

Works:
```lua
{
  foo = '<nop>'
}
```

Works:
```lua
{
  foo = '<nop>'
  bar = '<NOP>'
}
```

Does not work:
```lua
{
  foo = '<nop>',
  bar = '<nop>',
}
```

I used `foo` and `bar` as it doesn't matter which function I use here. My goal is to disable them all. I thought that it worked in the past by setting `keymaps = { }`, but apparently it gets merged now.
