### ISSUE TITLE
Use new `vim.ui.input` instead of `vim.fn.input`

### ISSUE THREAD

**Issue by IndianBoy42** [nvim-treesitter/nvim-treesitter-refactor#26]
**Is your feature request related to a problem? Please describe.**
`vim.ui.input` is a [newly merged](https://github.com/neovim/neovim/pull/15959) lua function for taking user text input. It is used by default in `vim.lsp.buf.rename()`. The advantage is it is 'overridable' with a custom lua function.

**Describe the solution you'd like**
Change [this line](https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/505e58a8b04596a073b326157490706ee63c3b81/lua/nvim-treesitter-refactor/smart_rename.lua#L22) to use `vim.ui.input`. The API is not exactly the same, you must provide an `on_confirm` callback to receive the user input.

**Comment by stsewd** [comment]
This should be done like https://github.com/nvim-treesitter/nvim-treesitter/pull/1892/, so it doesn't break on old versions of neovim.
